Bugfix/test system builder na cl
ADicksonLab/wepy pull request #131
Opened 2024-11-19 20:41 UTC by berkatik

This is a utility to build a NaCl pair system to use in tutorial documentation derived from Lennard-Jones particle system.

2024-12-02 16:02 UTC, salotz requested changes
Hi @berkatik I like the idea of adding NaCL as a test system.

It would have helped to have some extra context though, as I slowly discovered that you are using the same pattern for the openmmtools `TestSystem` (which was going to be my initial feedback upon scanning).

As you probably discovered I started putting similar systems in this project: [openmm_systems](https://github.com/ADicksonLab/openmm_systems).

While logically it should be maintained separately, I understand that it probably doesn't make sense to have that separated. So if you want to bring in some test systems directly to the wepy project I support that but I would request it be organized a little differently.

First, I would split it up so that it matches the module structure in `openmm_systems`, e.g. there is a `base.py` or similar which has the `TestSystem` base class, and then separate modules for the different test systems, i.e. `nacl_pair.py`.

Second, this should go under the `src/wepy_tools` module and not the core `src/wepy`. I try to constrain the necessary dependencies in core `src/wepy` so that it is easily installable and usable in different situations. I.e. you don't need OpenMM for doing analysis and OpenMM makes installation very difficult. And for modules that use OpenMM they have a special import guard to check for it.

I would suggest:

- `src/wepy_tools/systems/openmm`
  - `__init__.py`
  - `base.py`
  - `nacl_pair.py`
  - e.g. `lennard_jones.py`

Other than that see my inline suggestions.

2024-12-02 17:55 UTC, berkatik commented on src/wepy/util/test_system_builder.py
> +        scaleStepSizeZ = 1.0
Ok, I'll make sure to update these, thank you!

2025-01-17 15:14 UTC, berkatik commented
Finished moving the NaCl system to wepy_tools and made the updates for class default values and import alias. I tested it on the Wepy tutorial system.

2025-01-20 19:42 UTC, salotz approved these changes
LGTM. Thanks for incorporating!

2025-01-21 16:43 UTC, merged